### ISSUE TITLE
HOC를 제거하는게 좋을거 같네요.

### ISSUE THREAD

**Issue by denlyou** [incheonjs/react-idevs-materialui-admin-one#5]
https://github.com/incheonjs/react-idevs-materialui-admin-one/blob/fb41380901ec88e9f2872d5a2c4cf6fa3fbf71bd/src/components/pages/Tables.js#L85

Material-UI 4.x버전 부터는 HOC를 피하는 경향을 보이는거 같아서요. makeStyle을 사용하는 것으로 변경하는 것이 어떨까요?
리엑트 쪽에서도 이부분을 가능한 안쓰는 쪽으로 가는 분위기 같기도 하구요.

**Comment by adanbae** [comment]
네!!

**Comment by incheon-devs** [comment]
fixed #7
